name: workflow template 1

on:
  push:
    branches: [ test-branch ]
  pull_request:
    branches: [ test-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo This is the 1st workflow template!
